Dframework-ui latest changes
aasanntiwari/dframework-ui pull request #1
Opened 2024-01-12 05:22 UTC by Collins87mbathi

2024-02-01 06:54 UTC, Pramodspraxa requested changes

2024-02-01 06:54 UTC, Pramodspraxa commented on src/lib/components/Grid/CustomDropdownmenu.js
> +    gridFilterModelSelector,
Remove extra comma.

2024-02-01 06:54 UTC, Pramodspraxa commented on src/lib/components/Grid/CustomDropdownmenu.js
> +                    setIsMultiSelect(true)
semicolon missing.

2024-02-01 06:54 UTC, Pramodspraxa commented on src/lib/components/Grid/LocalizedDatePicker.js
> +        const isPartialDate = (value) => {
why function inside a function ?

2024-02-01 06:54 UTC, Pramodspraxa commented on src/lib/components/useRouter/StateProvider.js
> +    let params = {
params should be const

2024-02-01 06:54 UTC, Pramodspraxa commented on src/lib/components/useRouter/StateProvider.js
> +    let params = {
it should be const

2024-02-01 06:54 UTC, Pramodspraxa commented on src/lib/components/useRouter/stateReducer.js
> +                case actionsStateProvider.UPDATE_LOADER_STATE:
formatting missing.

2024-02-01 06:54 UTC, Pramodspraxa commented on src/lib/components/utils.js
> +        OverrideDateFormat: "DD-MMM-YYYY",
Remove extra comma

2024-02-01 08:05 UTC, Collins87mbathi commented on src/lib/components/Grid/LocalizedDatePicker.js
> +        const isPartialDate = (value) => {
thats how I found it written , I think its a conditional function

2024-02-02 07:07 UTC, aasanntiwari approved these changes

2024-02-02 07:07 UTC, merged